// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBiblioteczny.Data;

#nullable disable

namespace SystemBiblioteczny.Migrations
{
    [DbContext(typeof(BibliotekaDbContext))]
    [Migration("20260616141603_AktualizacjaBazy2")]
    partial class AktualizacjaBazy2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemBiblioteczny.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AutorId");

                    b.ToTable("Autorzy");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            Imie = "Andrzej",
                            Nazwisko = "Sapkowski"
                        },
                        new
                        {
                            AutorId = 2,
                            Imie = "Remigiusz",
                            Nazwisko = "Mróz"
                        },
                        new
                        {
                            AutorId = 3,
                            Imie = "Robert C.",
                            Nazwisko = "Martin"
                        });
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Bibliotekarz", b =>
                {
                    b.Property<int>("BibliotekarzeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BibliotekarzeId"));

                    b.Property<bool>("CzyAktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BibliotekarzeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Bibliotekarze");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Egzemplarz", b =>
                {
                    b.Property<int>("EgzemplarzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgzemplarzId"));

                    b.Property<int>("KsiazkaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Dostepny");

                    b.HasKey("EgzemplarzId");

                    b.HasIndex("KsiazkaId");

                    b.ToTable("Egzemplarze");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Kara", b =>
                {
                    b.Property<int>("KaraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KaraId"));

                    b.Property<int?>("BibliotekarzeId")
                        .HasColumnType("int");

                    b.Property<bool>("CzyOplacona")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataNalozenia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZaplaty")
                        .HasColumnType("date");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Powod")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("WypozyczanieId")
                        .HasColumnType("int");

                    b.HasKey("KaraId");

                    b.HasIndex("BibliotekarzeId");

                    b.HasIndex("UzytkownikId");

                    b.HasIndex("WypozyczanieId");

                    b.ToTable("Kary");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Kategoria", b =>
                {
                    b.Property<int>("KategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriaId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategoriaId");

                    b.HasIndex("Nazwa")
                        .IsUnique();

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            KategoriaId = 1,
                            Nazwa = "Fantastyka"
                        },
                        new
                        {
                            KategoriaId = 2,
                            Nazwa = "Kryminał"
                        },
                        new
                        {
                            KategoriaId = 3,
                            Nazwa = "Romans"
                        },
                        new
                        {
                            KategoriaId = 4,
                            Nazwa = "Historia"
                        },
                        new
                        {
                            KategoriaId = 5,
                            Nazwa = "Informatyka"
                        });
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Ksiazka", b =>
                {
                    b.Property<int>("KsiazkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KsiazkaId"));

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaEgzemplarzy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("RokWydania")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Wydawnictwo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KsiazkaId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Ksiazki");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.KsiazkaAutor", b =>
                {
                    b.Property<int>("KsiazkaId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.HasKey("KsiazkaId", "AutorId");

                    b.HasIndex("AutorId");

                    b.ToTable("KsiazkaAutorzy");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Rezerwacja", b =>
                {
                    b.Property<int>("RezerwacjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezerwacjaId"));

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataWaznosci")
                        .HasColumnType("date");

                    b.Property<int>("KsiazkaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aktywna");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("RezerwacjaId");

                    b.HasIndex("KsiazkaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Uzytkownik", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzytkownikId"));

                    b.Property<bool>("CzyAktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumerKarty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UzytkownikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumerKarty")
                        .IsUnique()
                        .HasFilter("[NumerKarty] IS NOT NULL");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("WypozyczanieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WypozyczanieId"));

                    b.Property<int?>("BibliotekarzeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataWypozyczenia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZwrotu")
                        .HasColumnType("date");

                    b.Property<int>("EgzemplarzId")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPrzedluzen")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PlanowanyZwrot")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aktywne");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("WypozyczanieId");

                    b.HasIndex("BibliotekarzeId");

                    b.HasIndex("EgzemplarzId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Egzemplarz", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Ksiazka", "Ksiazka")
                        .WithMany("Egzemplarze")
                        .HasForeignKey("KsiazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ksiazka");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Kara", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Bibliotekarz", "Bibliotekarz")
                        .WithMany("Kary")
                        .HasForeignKey("BibliotekarzeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SystemBiblioteczny.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Kary")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBiblioteczny.Models.Wypozyczenie", "Wypozyczenie")
                        .WithMany("Kary")
                        .HasForeignKey("WypozyczanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bibliotekarz");

                    b.Navigation("Uzytkownik");

                    b.Navigation("Wypozyczenie");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Ksiazka", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Kategoria", "Kategoria")
                        .WithMany("Ksiazki")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.KsiazkaAutor", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Autor", "Autor")
                        .WithMany("KsiazkaAutorzy")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBiblioteczny.Models.Ksiazka", "Ksiazka")
                        .WithMany("KsiazkaAutorzy")
                        .HasForeignKey("KsiazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Ksiazka");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Rezerwacja", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Ksiazka", "Ksiazka")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("KsiazkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBiblioteczny.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ksiazka");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Wypozyczenie", b =>
                {
                    b.HasOne("SystemBiblioteczny.Models.Bibliotekarz", "Bibliotekarz")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("BibliotekarzeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SystemBiblioteczny.Models.Egzemplarz", "Egzemplarz")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("EgzemplarzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBiblioteczny.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bibliotekarz");

                    b.Navigation("Egzemplarz");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Autor", b =>
                {
                    b.Navigation("KsiazkaAutorzy");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Bibliotekarz", b =>
                {
                    b.Navigation("Kary");

                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Egzemplarz", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Kategoria", b =>
                {
                    b.Navigation("Ksiazki");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Ksiazka", b =>
                {
                    b.Navigation("Egzemplarze");

                    b.Navigation("KsiazkaAutorzy");

                    b.Navigation("Rezerwacje");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Uzytkownik", b =>
                {
                    b.Navigation("Kary");

                    b.Navigation("Rezerwacje");

                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("SystemBiblioteczny.Models.Wypozyczenie", b =>
                {
                    b.Navigation("Kary");
                });
#pragma warning restore 612, 618
        }
    }
}
